#!/bin/sh
set -e

# Write runtime PocketBase URL into /srv/env.js.
# In the combined image PB_URL defaults to "" — the PocketBase JS SDK will
# use same-origin relative paths (/api/...) which Caddy proxies internally.
# Override PB_URL only if PocketBase is hosted on a different domain.
cat > /srv/env.js << EOF
// Generated by docker-entrypoint.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
window.__ENV__ = {
  PB_URL: "${PB_URL:-}"
};
EOF

# Start PocketBase in the background
/app/pocketbase_app serve \
    --http=0.0.0.0:8090 \
    --dir=/app/pb_data &

# Start Caddy in the foreground (becomes PID 1, receives signals)
exec caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
