// Package migrations contains all database migrations for the MKZ PocketBase backend.
//
// Migration 1747483200_create_kennzeichen:
//   - Creates the `kennzeichen` collection
//   - Seeds it with ALL German Kfz-Kennzeichen (Unterscheidungszeichen)
//
// Data source: https://github.com/openpotato/kfz-kennzeichen (MIT licence)
// Cross-referenced with: https://de.wikipedia.org/wiki/Liste_der_deutschen_Landkreise_und_Städte_mit_ihren_Kfz-Kennzeichen
package migrations

import (
	"github.com/pocketbase/pocketbase/core"
	m "github.com/pocketbase/pocketbase/migrations"
	"github.com/pocketbase/pocketbase/tools/types"
)

// kennzeichenRow holds one entry from the Kfz-Kennzeichen dataset.
type kennzeichenRow struct {
	// Code is the 1–3 letter plate prefix (Unterscheidungszeichen), e.g. "M", "KA", "B".
	Code string
	// District is the current Zulassungsbezirk (district/city name).
	// Multiple districts sharing the same code are joined with " / ".
	District string
	// Bundesland is the German state full name, e.g. "Bayern".
	Bundesland string
	// BundeslandISO is the ISO 3166-2 state code, e.g. "DE-BY".
	BundeslandISO string
	// Derivation shows how the abbreviation was derived from the place name.
	Derivation string
	// Active is false for codes that are being phased out ("auslaufend").
	Active bool
	// Notes contains any special remarks (e.g. phase-out information).
	Notes string
}

// kennzeichenData is the complete, authoritative list of German Kfz-Kennzeichen.
// Total: 833 entries (current + phase-out codes).
// Last updated: 2026-05-17 from openpotato/kfz-kennzeichen (MIT).
var kennzeichenData = []kennzeichenRow{
	{"A", "Augsburg", "Bayern", "DE-BY", "Augsburg", true, ""},
	{"AA", "Ostalbkreis", "Baden-Württemberg", "DE-BW", "AAlen", true, ""},
	{"AB", "Aschaffenburg", "Bayern", "DE-BY", "AschaffenBurg", true, ""},
	{"ABG", "Altenburger Land", "Thüringen", "DE-TH", "AltenBurG", true, ""},
	{"ABI", "Anhalt-Bitterfeld", "Sachsen-Anhalt", "DE-ST", "Anhalt-BItterfeld", true, ""},
	{"AC", "Aachen", "Nordrhein-Westfalen", "DE-NW", "AaChen", true, ""},
	{"AE", "Vogtlandkreis", "Sachsen", "DE-SN", "AuErbach", true, ""},
	{"AH", "Borken", "Nordrhein-Westfalen", "DE-NW", "AHaus", true, ""},
	{"AIB", "München / Rosenheim", "Bayern", "DE-BY", "AIBling", true, ""},
	{"AIC", "Aichach-Friedberg", "Bayern", "DE-BY", "AIChach", true, ""},
	{"AK", "Altenkirchen (Westerwald)", "Rheinland-Pfalz", "DE-RP", "AltenKirchen", true, ""},
	{"ALF", "Hildesheim", "Niedersachsen", "DE-NI", "ALFeld", true, ""},
	{"ALZ", "Aschaffenburg", "Bayern", "DE-BY", "ALZenau", true, ""},
	{"AM", "Amberg, Stadt", "Bayern", "DE-BY", "AMberg", false, "auslaufend – Abwicklung: Zulassungsbehörde Amberg-Sulzbach"},
	{"AN", "Ansbach", "Bayern", "DE-BY", "ANsbach", true, ""},
	{"ANA", "Erzgebirgskreis", "Sachsen", "DE-SN", "ANnAberg", true, ""},
	{"ANG", "Uckermark", "Brandenburg", "DE-BB", "ANGermünde", true, ""},
	{"ANK", "Vorpommern-Greifswald", "Mecklenburg-Vorpommern", "DE-MV", "ANKlam", true, ""},
	{"AP", "Weimarer Land", "Thüringen", "DE-TH", "APolda", true, ""},
	{"APD", "Weimarer Land", "Thüringen", "DE-TH", "APolDa", true, ""},
	{"ARN", "Ilm-Kreis", "Thüringen", "DE-TH", "ARNstadt", true, ""},
	{"ART", "Kyffhäuserkreis", "Thüringen", "DE-TH", "ARTern", true, ""},
	{"AS", "Amberg-Sulzbach", "Bayern", "DE-BY", "Amberg, Sulzbach", true, ""},
	{"ASL", "Salzlandkreis", "Sachsen-Anhalt", "DE-ST", "ASchersLeben", true, ""},
	{"ASZ", "Erzgebirgskreis", "Sachsen", "DE-SN", "Aue, SchwarZenberg", true, ""},
	{"AT", "Mecklenburgische Seenplatte", "Mecklenburg-Vorpommern", "DE-MV", "AltenTreptow", true, ""},
	{"AU", "Erzgebirgskreis", "Sachsen", "DE-SN", "AUe", true, ""},
	{"AUR", "Aurich", "Niedersachsen", "DE-NI", "AURich", true, ""},
	{"AW", "Ahrweiler", "Rheinland-Pfalz", "DE-RP", "AhrWeiler", true, ""},
	{"AZ", "Alzey-Worms", "Rheinland-Pfalz", "DE-RP", "AlZey", true, ""},
	{"AZE", "Anhalt-Bitterfeld", "Sachsen-Anhalt", "DE-ST", "Landkreis Anhalt-ZErbst (bis 2007)", true, ""},
	{"AÖ", "Altötting", "Bayern", "DE-BY", "AltÖtting", true, ""},
	{"B", "Berlin", "Berlin", "DE-BE", "Berlin", true, ""},
	{"BA", "Bamberg", "Bayern", "DE-BY", "BAmberg", true, ""},
	{"BAD", "Baden-Baden, Stadt", "Baden-Württemberg", "DE-BW", "BADen-Baden", true, ""},
	{"BAR", "Barnim", "Brandenburg", "DE-BB", "BARnim", true, ""},
	{"BB", "Böblingen", "Baden-Württemberg", "DE-BW", "BöBlingen", true, ""},
	{"BBG", "Salzlandkreis", "Sachsen-Anhalt", "DE-ST", "BernBurG", true, ""},
	{"BC", "Biberach", "Baden-Württemberg", "DE-BW", "BiberaCh", true, ""},
	{"BCH", "Neckar-Odenwald-Kreis", "Baden-Württemberg", "DE-BW", "BuCHen", true, ""},
	{"BE", "Warendorf", "Nordrhein-Westfalen", "DE-NW", "BEckum", true, ""},
	{"BED", "Mittelsachsen", "Sachsen", "DE-SN", "Brand-ErbisDorf", true, ""},
	{"BEL", "Potsdam-Mittelmark", "Brandenburg", "DE-BB", "BELzig", true, ""},
	{"BER", "Barnim", "Brandenburg", "DE-BB", "BERnau", true, ""},
	{"BF", "Steinfurt", "Nordrhein-Westfalen", "DE-NW", "BurgsteinFurt", true, ""},
	{"BGD", "Berchtesgadener Land", "Bayern", "DE-BY", "BerchtesGaDen", true, ""},
	{"BGL", "Berchtesgadener Land", "Bayern", "DE-BY", "BerchtesGadener Land", true, ""},
	{"BH", "Ortenaukreis / Rastatt", "Baden-Württemberg", "DE-BW", "BüHl", true, ""},
	{"BI", "Bielefeld, Stadt", "Nordrhein-Westfalen", "DE-NW", "BIelefeld", true, ""},
	{"BID", "Marburg-Biedenkopf", "Hessen", "DE-HE", "BIeDenkopf", true, ""},
	{"BIN", "Mainz-Bingen", "Rheinland-Pfalz", "DE-RP", "BINgen", true, ""},
	{"BIR", "Birkenfeld", "Rheinland-Pfalz", "DE-RP", "BIRkenfeld", true, ""},
	{"BIT", "Eifelkreis Bitburg-Prüm", "Rheinland-Pfalz", "DE-RP", "BITburg", true, ""},
	{"BIW", "Bautzen", "Sachsen", "DE-SN", "BIschofsWerda", true, ""},
	{"BK", "Börde / Rems-Murr-Kreis / Schwäbisch Hall", "Baden-Württemberg", "DE-BW", "BacKnang", true, ""},
	{"BKS", "Bernkastel-Wittlich", "Rheinland-Pfalz", "DE-RP", "BernKaStel", true, ""},
	{"BL", "Zollernalbkreis", "Baden-Württemberg", "DE-BW", "BaLingen", true, ""},
	{"BLB", "Siegen-Wittgenstein", "Nordrhein-Westfalen", "DE-NW", "BerLeBurg", true, ""},
	{"BLK", "Burgenlandkreis", "Sachsen-Anhalt", "DE-ST", "BurgenLandKreis", true, ""},
	{"BM", "Rhein-Erft-Kreis", "Nordrhein-Westfalen", "DE-NW", "BergheiM", true, ""},
	{"BN", "Bonn, Stadt", "Nordrhein-Westfalen", "DE-NW", "BonN", true, ""},
	{"BNA", "Leipzig", "Sachsen", "DE-SN", "BorNA", true, ""},
	{"BO", "Bochum, Stadt", "Nordrhein-Westfalen", "DE-NW", "BOchum", true, ""},
	{"BOG", "Straubing-Bogen", "Bayern", "DE-BY", "BOGen", true, ""},
	{"BOH", "Borken", "Nordrhein-Westfalen", "DE-NW", "BOcHolt", true, ""},
	{"BOR", "Borken", "Nordrhein-Westfalen", "DE-NW", "BORken", true, ""},
	{"BOT", "Bottrop, Stadt", "Nordrhein-Westfalen", "DE-NW", "BOTtrop", true, ""},
	{"BR", "Landkreis Karlsruhe", "Baden-Württemberg", "DE-BW", "BRuchsal", true, ""},
	{"BRA", "Wesermarsch", "Niedersachsen", "DE-NI", "BRAke", true, ""},
	{"BRB", "Brandenburg, Stadt", "Brandenburg", "DE-BB", "BRandenBurg", false, "auslaufend – Abwicklung: Zulassungsbehörde Potsdam-Mittelmark"},
	{"BRG", "Jerichower Land", "Sachsen-Anhalt", "DE-ST", "BuRG", true, ""},
	{"BRK", "Bad Kissingen", "Bayern", "DE-BY", "BRücKenau", true, ""},
	{"BRL", "Goslar", "Niedersachsen", "DE-NI", "BRaunLage", true, ""},
	{"BRV", "Rotenburg (Wümme)", "Niedersachsen", "DE-NI", "BRemerVörde", true, ""},
	{"BS", "Braunschweig, Stadt", "Niedersachsen", "DE-NI", "BraunSchweig", true, ""},
	{"BSB", "Osnabrück", "Niedersachsen", "DE-NI", "BerSenBrück", true, ""},
	{"BSK", "Oder-Spree", "Brandenburg", "DE-BB", "BeeSKow", true, ""},
	{"BT", "Bayreuth", "Bayern", "DE-BY", "BayreuTh", true, ""},
	{"BTF", "Anhalt-Bitterfeld", "Sachsen-Anhalt", "DE-ST", "BitTerFeld", true, ""},
	{"BUL", "Amberg-Sulzbach / Schwandorf", "Bayern", "DE-BY", "BUrgLengenfeld", true, ""},
	{"BZ", "Bautzen", "Sachsen", "DE-SN", "BautZen", true, ""},
	{"BÖ", "Börde", "Sachsen-Anhalt", "DE-ST", "BÖrde", true, ""},
	{"BÜD", "Wetteraukreis", "Hessen", "DE-HE", "BÜDingen", true, ""},
	{"BÜR", "Paderborn", "Nordrhein-Westfalen", "DE-NW", "BÜRen", true, ""},
	{"BÜS", "Konstanz / Gemeinde Büsingen am Hochrhein", "Baden-Württemberg", "DE-BW", "BÜSingen", true, ""},
	{"BÜZ", "Rostock, Landkreis", "Mecklenburg-Vorpommern", "DE-MV", "BÜtZow", true, ""},
	{"C", "Chemnitz, Stadt", "Sachsen", "DE-SN", "Chemnitz", false, "auslaufend – Abwicklung: Zulassungsbehörde Zwickau"},
	{"CA", "Oberspreewald-Lausitz", "Brandenburg", "DE-BB", "CAlau", true, ""},
	{"CAS", "Recklinghausen", "Nordrhein-Westfalen", "DE-NW", "CAStrop", true, ""},
	{"CB", "Cottbus, Stadt", "Brandenburg", "DE-BB", "CottBus", false, "auslaufend – Abwicklung: Zulassungsbehörde Spree-Neiße"},
	{"CE", "Celle", "Niedersachsen", "DE-NI", "CElle", true, ""},
	{"CHA", "Cham", "Bayern", "DE-BY", "CHAm", true, ""},
	{"CLP", "Cloppenburg", "Niedersachsen", "DE-NI", "CLopPenburg", true, ""},
	{"CLZ", "Goslar", "Niedersachsen", "DE-NI", "CLausthal-Zellerfeld", true, ""},
	{"CO", "Zulassungsstelle Coburg, Zweckverband", "Bayern", "DE-BY", "COburg", true, ""},
	{"COC", "Cochem-Zell", "Rheinland-Pfalz", "DE-RP", "COChem", true, ""},
	{"COE", "Coesfeld", "Nordrhein-Westfalen", "DE-NW", "COEsfeld", true, ""},
	{"CR", "Schwäbisch Hall", "Baden-Württemberg", "DE-BW", "CRailsheim", true, ""},
	{"CUX", "Cuxhaven", "Niedersachsen", "DE-NI", "CUXhaven", true, ""},
	{"CW", "Calw", "Baden-Württemberg", "DE-BW", "CalW", true, ""},
	{"D", "Düsseldorf, Stadt", "Nordrhein-Westfalen", "DE-NW", "Düsseldorf", true, ""},
	{"DA", "Darmstadt", "Hessen", "DE-HE", "DArmstadt", true, ""},
	{"DAH", "Dachau", "Bayern", "DE-BY", "DAcHau", true, ""},
	{"DAN", "Lüchow-Dannenberg", "Niedersachsen", "DE-NI", "DANnenberg", true, ""},
	{"DAU", "Vulkaneifel", "Rheinland-Pfalz", "DE-RP", "DAUn", true, ""},
	{"DBR", "Rostock, Landkreis", "Mecklenburg-Vorpommern", "DE-MV", "DoBeRan", true, ""},
	{"DD", "Dresden, Stadt", "Sachsen", "DE-SN", "DresDen", true, ""},
	{"DE", "Dessau-Roßlau, Stadt", "Sachsen-Anhalt", "DE-ST", "DEssau", true, ""},
	{"DEG", "Deggendorf", "Bayern", "DE-BY", "DEGgendorf", true, ""},
	{"DEL", "Delmenhorst, Stadt", "Niedersachsen", "DE-NI", "DELmenhorst", true, ""},
	{"DGF", "Dingolfing-Landau", "Bayern", "DE-BY", "DinGolFing", true, ""},
	{"DH", "Diepholz", "Niedersachsen", "DE-NI", "DiepHolz", true, ""},
	{"DI", "Darmstadt-Dieburg", "Hessen", "DE-HE", "DIeburg", true, ""},
	{"DIL", "Lahn-Dill-Kreis", "Hessen", "DE-HE", "DILlenburg", true, ""},
	{"DIN", "Wesel", "Nordrhein-Westfalen", "DE-NW", "DINslaken", true, ""},
	{"DIZ", "Rhein-Lahn-Kreis", "Rheinland-Pfalz", "DE-RP", "DIeZ", true, ""},
	{"DKB", "Ansbach", "Bayern", "DE-BY", "DinKelsBühl", true, ""},
	{"DL", "Mittelsachsen", "Sachsen", "DE-SN", "DöbeLn", true, ""},
	{"DLG", "Dillingen an der Donau", "Bayern", "DE-BY", "DilLinGen", true, ""},
	{"DM", "Mecklenburgische Seenplatte", "Mecklenburg-Vorpommern", "DE-MV", "DemMin", true, ""},
	{"DN", "Düren", "Nordrhein-Westfalen", "DE-NW", "DüreN", true, ""},
	{"DO", "Dortmund, Stadt", "Nordrhein-Westfalen", "DE-NW", "DOrtmund", true, ""},
	{"DON", "Donau-Ries", "Bayern", "DE-BY", "DONauwörth", true, ""},
	{"DS", "Schwarzwald-Baar-Kreis", "Baden-Württemberg", "DE-BW", "DonaueSchingen", true, ""},
	{"DU", "Duisburg, Stadt", "Nordrhein-Westfalen", "DE-NW", "DUisburg", true, ""},
	{"DUD", "Göttingen", "Niedersachsen", "DE-NI", "DUDerstadt", true, ""},
	{"DW", "Sächsische Schweiz-Osterzgebirge", "Sachsen", "DE-SN", "DippoldisWalde", true, ""},
	{"DZ", "Nordsachsen", "Sachsen", "DE-SN", "DelitZsch", true, ""},
	{"DÜW", "Bad Dürkheim", "Rheinland-Pfalz", "DE-RP", "DÜrkheim an der Weinstraße", true, ""},
	{"E", "Essen, Stadt", "Nordrhein-Westfalen", "DE-NW", "Essen", true, ""},
	{"EA", "Wartburgkreis", "Thüringen", "DE-TH", "EisenAch", true, ""},
	{"EB", "Nordsachsen", "Sachsen", "DE-SN", "EilenBurg", true, ""},
	{"EBE", "Ebersberg", "Bayern", "DE-BY", "EBErsberg", true, ""},
	{"EBN", "Haßberge", "Bayern", "DE-BY", "EBerN", true, ""},
	{"EBS", "Bayreuth / Forchheim / Kulmbach", "Bayern", "DE-BY", "EBermannStadt", true, ""},
	{"ECK", "Rendsburg-Eckernförde", "Schleswig-Holstein", "DE-SH", "ECKernförde", true, ""},
	{"ED", "Erding", "Bayern", "DE-BY", "ErDing", true, ""},
	{"EE", "Elbe-Elster", "Brandenburg", "DE-BB", "Elbe, Elster", true, ""},
	{"EF", "Erfurt, Stadt", "Thüringen", "DE-TH", "ErFurt", false, "auslaufend – Abwicklung: Zulassungsbehörde Sömmerda"},
	{"EG", "Rottal-Inn", "Bayern", "DE-BY", "EGgenfelden", true, ""},
	{"EH", "Oder-Spree", "Brandenburg", "DE-BB", "EisenHüttenstadt", true, ""},
	{"EI", "Eichstätt", "Bayern", "DE-BY", "EIchstätt", true, ""},
	{"EIC", "Eichsfeld", "Thüringen", "DE-TH", "EIChsfeld", true, ""},
	{"EIL", "Mansfeld-Südharz", "Sachsen-Anhalt", "DE-ST", "EIsLeben", true, ""},
	{"EIN", "Northeim", "Niedersachsen", "DE-NI", "EINbeck", true, ""},
	{"EIS", "Saale-Holzland-Kreis", "Thüringen", "DE-TH", "EISenberg", true, ""},
	{"EL", "Emsland", "Niedersachsen", "DE-NI", "EmsLand", true, ""},
	{"EM", "Emmendingen", "Baden-Württemberg", "DE-BW", "EMmendingen", true, ""},
	{"EMD", "Emden, Stadt", "Niedersachsen", "DE-NI", "EMDen", true, ""},
	{"EMS", "Rhein-Lahn-Kreis", "Rheinland-Pfalz", "DE-RP", "EMS", true, ""},
	{"EN", "Ennepe-Ruhr-Kreis", "Nordrhein-Westfalen", "DE-NW", "ENnepe", true, ""},
	{"ER", "Erlangen, Stadt", "Bayern", "DE-BY", "ERlangen", false, "auslaufend – Abwicklung: Zulassungsbehörde Erlangen-Höchstadt"},
	{"ERB", "Odenwaldkreis", "Hessen", "DE-HE", "ERBach", true, ""},
	{"ERH", "Erlangen-Höchstadt", "Bayern", "DE-BY", "ERlangen, Höchstadt", true, ""},
	{"ERK", "Heinsberg", "Nordrhein-Westfalen", "DE-NW", "ERKelenz", true, ""},
	{"ERZ", "Erzgebirgskreis", "Sachsen", "DE-SN", "ERZgebirge", true, ""},
	{"ES", "Esslingen", "Baden-Württemberg", "DE-BW", "ESslingen", true, ""},
	{"ESB", "Amberg-Sulzbach / Bayreuth / Neustadt a. d. Waldnaab / Nürnberger Land", "Bayern", "DE-BY", "ESchenBach", true, ""},
	{"ESW", "Werra-Meißner-Kreis", "Hessen", "DE-HE", "ESchWege", true, ""},
	{"EU", "Euskirchen", "Nordrhein-Westfalen", "DE-NW", "EUskirchen", true, ""},
	{"EW", "Barnim", "Brandenburg", "DE-BB", "EbersWalde", true, ""},
	{"F", "Frankfurt/Main, Stadt", "Hessen", "DE-HE", "Frankfurt", true, ""},
	{"FB", "Wetteraukreis", "Hessen", "DE-HE", "FriedBerg", true, ""},
	{"FD", "Fulda", "Hessen", "DE-HE", "FulDa", true, ""},
	{"FDB", "Aichach-Friedberg", "Bayern", "DE-BY", "FrieDBerg", true, ""},
	{"FDS", "Freudenstadt", "Baden-Württemberg", "DE-BW", "FreuDenStadt", true, ""},
	{"FEU", "Ansbach", "Bayern", "DE-BY", "FEUchtwangen", true, ""},
	{"FF", "Frankfurt (Oder), Stadt", "Brandenburg", "DE-BB", "FrankFurt", true, ""},
	{"FFB", "Fürstenfeldbruck", "Bayern", "DE-BY", "FürstenFeldBruck", true, ""},
	{"FG", "Mittelsachsen", "Sachsen", "DE-SN", "FreiberG", true, ""},
	{"FI", "Elbe-Elster", "Brandenburg", "DE-BB", "FInsterwalde", true, ""},
	{"FKB", "Waldeck-Frankenberg", "Hessen", "DE-HE", "FranKenBerg", true, ""},
	{"FL", "Flensburg", "Schleswig-Holstein", "DE-SH", "FLensburg", true, ""},
	{"FLÖ", "Mittelsachsen", "Sachsen", "DE-SN", "FLÖha", true, ""},
	{"FN", "Bodenseekreis", "Baden-Württemberg", "DE-BW", "FriedrichshafeN", true, ""},
	{"FO", "Forchheim", "Bayern", "DE-BY", "FOrchheim", true, ""},
	{"FOR", "Spree-Neiße", "Brandenburg", "DE-BB", "FORst", true, ""},
	{"FR", "Freiburg im Breisgau, Stadt / Breisgau-Hochschwarzwald", "Baden-Württemberg", "DE-BW", "FReiburg", true, ""},
	{"FRG", "Freyung-Grafenau", "Bayern", "DE-BY", "FReyung, Grafenau", true, ""},
	{"FRI", "Friesland", "Niedersachsen", "DE-NI", "FRIesland", true, ""},
	{"FRW", "Märkisch-Oderland", "Brandenburg", "DE-BB", "FReienWalde", true, ""},
	{"FS", "Freising", "Bayern", "DE-BY", "FreiSing", true, ""},
	{"FT", "Frankenthal (Pfalz), Stadt", "Rheinland-Pfalz", "DE-RP", "FrankenThal", false, "auslaufend – Abwicklung: Zulassungsbehörde Bad Dürkheim und Rhein-Pfalz-Kreis"},
	{"FTL", "Sächsische Schweiz-Osterzgebirge", "Sachsen", "DE-SN", "FreiTaL", true, ""},
	{"FW", "Oder-Spree", "Brandenburg", "DE-BB", "FürstenWalde", true, ""},
	{"FZ", "Schwalm-Eder-Kreis", "Hessen", "DE-HE", "FritZlar", true, ""},
	{"FÜ", "Fürth", "Bayern", "DE-BY", "FÜrth", true, ""},
	{"FÜS", "Ostallgäu", "Bayern", "DE-BY", "FÜSsen", true, ""},
	{"G", "Gera, Stadt", "Thüringen", "DE-TH", "Gera", false, "auslaufend – Abwicklung: Zulassungsbehörde Greiz"},
	{"GA", "Altmarkkreis Salzwedel", "Sachsen-Anhalt", "DE-ST", "GArdelegen", true, ""},
	{"GAN", "Northeim", "Niedersachsen", "DE-NI", "GANdersheim", true, ""},
	{"GAP", "Garmisch-Partenkirchen", "Bayern", "DE-BY", "GArmisch-Partenkirchen", true, ""},
	{"GC", "Zwickau", "Sachsen", "DE-SN", "GlauChau", true, ""},
	{"GD", "Ostalbkreis", "Baden-Württemberg", "DE-BW", "GmünD", true, ""},
	{"GDB", "Nordwestmecklenburg", "Mecklenburg-Vorpommern", "DE-MV", "GaDeBusch", true, ""},
	{"GE", "Gelsenkirchen, Stadt", "Nordrhein-Westfalen", "DE-NW", "GElsenkirchen", true, ""},
	{"GEL", "Kleve", "Nordrhein-Westfalen", "DE-NW", "GELdern", true, ""},
	{"GEO", "Haßberge / Schweinfurt", "Bayern", "DE-BY", "GErOlzhofen", true, ""},
	{"GER", "Germersheim", "Rheinland-Pfalz", "DE-RP", "GERmersheim", true, ""},
	{"GF", "Gifhorn", "Niedersachsen", "DE-NI", "GiFhorn", true, ""},
	{"GG", "Groß-Gerau", "Hessen", "DE-HE", "Groß-Gerau", true, ""},
	{"GHA", "Leipzig", "Sachsen", "DE-SN", "GeitHAin", true, ""},
	{"GHC", "Wittenberg", "Sachsen-Anhalt", "DE-ST", "GräfenHainiChen", true, ""},
	{"GI", "Gießen", "Hessen", "DE-HE", "GIeßen", true, ""},
	{"GK", "Heinsberg", "Nordrhein-Westfalen", "DE-NW", "GeilenKirchen", true, ""},
	{"GL", "Rheinisch-Bergischer Kreis", "Nordrhein-Westfalen", "DE-NW", "GLadbach", true, ""},
	{"GLA", "Recklinghausen", "Nordrhein-Westfalen", "DE-NW", "GLAdbeck", true, ""},
	{"GM", "Oberbergischer Kreis", "Nordrhein-Westfalen", "DE-NW", "GumMersbach", true, ""},
	{"GMN", "Vorpommern-Rügen", "Mecklenburg-Vorpommern", "DE-MV", "GrimMeN", true, ""},
	{"GN", "Main-Kinzig-Kreis", "Hessen", "DE-HE", "GelnhauseN", true, ""},
	{"GNT", "Jerichower Land", "Sachsen-Anhalt", "DE-ST", "GeNThin", true, ""},
	{"GOA", "Rhein-Hunsrück-Kreis", "Rheinland-Pfalz", "DE-RP", "Sankt GOAr", true, ""},
	{"GOH", "Rhein-Lahn-Kreis", "Rheinland-Pfalz", "DE-RP", "Sankt GOarsHausen", true, ""},
	{"GP", "Göppingen", "Baden-Württemberg", "DE-BW", "GöpPingen", true, ""},
	{"GR", "Görlitz", "Sachsen", "DE-SN", "GöRlitz", true, ""},
	{"GRA", "Freyung-Grafenau", "Bayern", "DE-BY", "GRAfenau", true, ""},
	{"GRH", "Meißen", "Sachsen", "DE-SN", "GRoßenHain", true, ""},
	{"GRI", "Rottal-Inn", "Bayern", "DE-BY", "GRIesbach", true, ""},
	{"GRM", "Leipzig", "Sachsen", "DE-SN", "GRimMa", true, ""},
	{"GRZ", "Greiz", "Thüringen", "DE-TH", "GReiZ", true, ""},
	{"GS", "Goslar", "Niedersachsen", "DE-NI", "GoSlar", true, ""},
	{"GT", "Gütersloh", "Nordrhein-Westfalen", "DE-NW", "GüTersloh", true, ""},
	{"GTH", "Gotha", "Thüringen", "DE-TH", "GoTHa", true, ""},
	{"GUB", "Spree-Neiße", "Brandenburg", "DE-BB", "GUBen", true, ""},
	{"GUN", "Weißenburg-Gunzenhausen", "Bayern", "DE-BY", "GUNzenhausen", true, ""},
	{"GV", "Rhein-Kreis Neuss", "Nordrhein-Westfalen", "DE-NW", "GreVenbroich", true, ""},
	{"GVM", "Nordwestmecklenburg", "Mecklenburg-Vorpommern", "DE-MV", "GreVesMühlen", true, ""},
	{"GW", "Vorpommern-Greifswald", "Mecklenburg-Vorpommern", "DE-MV", "GreifsWald", true, ""},
	{"GZ", "Günzburg", "Bayern", "DE-BY", "GünZburg", true, ""},
	{"GÖ", "Göttingen", "Niedersachsen", "DE-NI", "GÖttingen", true, ""},
	{"GÜ", "Landkreis Rostock", "Mecklenburg-Vorpommern", "DE-MV", "GÜstrow", true, ""},
	{"H", "Hannover", "Niedersachsen", "DE-NI", "Hannover", true, ""},
	{"HA", "Hagen, Stadt", "Nordrhein-Westfalen", "DE-NW", "HAgen", true, ""},
	{"HAB", "Bad Kissingen", "Bayern", "DE-BY", "HAmmelBurg", true, ""},
	{"HAL", "Halle, Stadt", "Sachsen-Anhalt", "DE-ST", "HALle", true, ""},
	{"HAM", "Hamm, Stadt", "Nordrhein-Westfalen", "DE-NW", "HAMm", true, ""},
	{"HAS", "Haßberge", "Bayern", "DE-BY", "HASsfurt", true, ""},
	{"HB", "Freie Hansestadt Bremen", "Bremen", "DE-HB", "Hansestadt Bremen", true, ""},
	{"HBN", "Hildburghausen", "Thüringen", "DE-TH", "HildBurghauseN", true, ""},
	{"HBS", "Harz", "Sachsen-Anhalt", "DE-ST", "HalBerStadt", true, ""},
	{"HC", "Mittelsachsen", "Sachsen", "DE-SN", "HainiChen", true, ""},
	{"HCH", "Freudenstadt / Zollernalbkreis", "Baden-Württemberg", "DE-BW", "HeCHingen", true, ""},
	{"HD", "Heidelberg, Stadt / Rhein-Neckar-Kreis", "Baden-Württemberg", "DE-BW", "HeiDelberg", true, ""},
	{"HDH", "Heidenheim", "Baden-Württemberg", "DE-BW", "HeiDenHeim", true, ""},
	{"HDL", "Börde", "Sachsen-Anhalt", "DE-ST", "HalDensLeben", true, ""},
	{"HE", "Helmstedt", "Niedersachsen", "DE-NI", "HElmstedt", true, ""},
	{"HEB", "Nürnberger Land", "Bayern", "DE-BY", "HErsBruck", true, ""},
	{"HEF", "Hersfeld-Rotenburg", "Hessen", "DE-HE", "HErsFeld", true, ""},
	{"HEI", "Dithmarschen", "Schleswig-Holstein", "DE-SH", "HEIde", true, ""},
	{"HER", "Herne, Stadt", "Nordrhein-Westfalen", "DE-NW", "HERne", true, ""},
	{"HET", "Mansfeld-Südharz", "Sachsen-Anhalt", "DE-ST", "HETtstedt", true, ""},
	{"HF", "Herford", "Nordrhein-Westfalen", "DE-NW", "HerFord", true, ""},
	{"HG", "Hochtaunuskreis", "Hessen", "DE-HE", "HomburG", true, ""},
	{"HGN", "Ludwigslust-Parchim", "Mecklenburg-Vorpommern", "DE-MV", "HaGeNow", true, ""},
	{"HGW", "Hansestadt Greifswald", "Mecklenburg-Vorpommern", "DE-MV", "Hansestadt GreifsWald", true, ""},
	{"HH", "Freie und Hansestadt Hamburg", "Hamburg", "DE-HH", "Hansestadt Hamburg", true, ""},
	{"HHM", "Burgenlandkreis", "Sachsen-Anhalt", "DE-ST", "HoHenMölsen", true, ""},
	{"HI", "Hildesheim", "Niedersachsen", "DE-NI", "HIldesheim", true, ""},
	{"HIG", "Eichsfeld", "Thüringen", "DE-TH", "HeilIGenstadt", true, ""},
	{"HIP", "Roth", "Bayern", "DE-BY", "HIlPoltstein", true, ""},
	{"HK", "Heidekreis", "Niedersachsen", "DE-NI", "HeideKreis", true, ""},
	{"HL", "Hansestadt Lübeck", "Schleswig-Holstein", "DE-SH", "Hansestadt Lübeck", true, ""},
	{"HM", "Hameln-Pyrmont", "Niedersachsen", "DE-NI", "HaMeln", true, ""},
	{"HMÜ", "Göttingen", "Niedersachsen", "DE-NI", "Hann. MÜnden", true, ""},
	{"HN", "Heilbronn", "Baden-Württemberg", "DE-BW", "HeilbronN", true, ""},
	{"HO", "Hof", "Bayern", "DE-BY", "HOf", true, ""},
	{"HOG", "Kassel", "Hessen", "DE-HE", "HOfGeismar", true, ""},
	{"HOH", "Haßberge", "Bayern", "DE-BY", "HOfHeim", true, ""},
	{"HOL", "Holzminden", "Niedersachsen", "DE-NI", "HOLzminden", true, ""},
	{"HOM", "Saarpfalz-Kreis", "Saarland", "DE-SL", "HOMburg", true, ""},
	{"HOR", "Freudenstadt", "Baden-Württemberg", "DE-BW", "HORb", true, ""},
	{"HOT", "Zwickau", "Sachsen", "DE-SN", "HOhensTein", true, ""},
	{"HP", "Bergstraße", "Hessen", "DE-HE", "HepPenheim", true, ""},
	{"HR", "Schwalm-Eder-Kreis", "Hessen", "DE-HE", "HombeRg", true, ""},
	{"HRO", "Hansestadt Rostock", "Mecklenburg-Vorpommern", "DE-MV", "Hansestadt ROstock", true, ""},
	{"HS", "Heinsberg", "Nordrhein-Westfalen", "DE-NW", "HeinSberg", true, ""},
	{"HSK", "Hochsauerlandkreis", "Nordrhein-Westfalen", "DE-NW", "HochSauerlandKreis", true, ""},
	{"HST", "Hansestadt Stralsund, Stadt", "Mecklenburg-Vorpommern", "DE-MV", "Hansestadt STralsund", false, "auslaufend – Abwicklung: Zulassungsbehörde Vorpommern-Rügen"},
	{"HU", "Hanau / Main-Kinzig-Kreis", "Hessen", "DE-HE", "HanaU", true, ""},
	{"HV", "Stendal", "Sachsen-Anhalt", "DE-ST", "HaVelberg", true, ""},
	{"HVL", "Havelland", "Brandenburg", "DE-BB", "HaVelLand", true, ""},
	{"HWI", "Hansestadt Wismar", "Mecklenburg-Vorpommern", "DE-MV", "Hansestadt WIsmar", true, ""},
	{"HX", "Höxter", "Nordrhein-Westfalen", "DE-NW", "HöXter", true, ""},
	{"HY", "Bautzen", "Sachsen", "DE-SN", "HoYerswerda", true, ""},
	{"HZ", "Harz", "Sachsen-Anhalt", "DE-ST", "HarZ", true, ""},
	{"HÖS", "Erlangen-Höchstadt", "Bayern", "DE-BY", "HÖchStadt", true, ""},
	{"IGB", "St. Ingbert, Stadt", "Saarland", "DE-SL", "InGBert", true, ""},
	{"IK", "Ilm-Kreis", "Thüringen", "DE-TH", "Ilm-Kreis", true, ""},
	{"IL", "Ilm-Kreis", "Thüringen", "DE-TH", "ILmenau", true, ""},
	{"ILL", "Neu-Ulm", "Bayern", "DE-BY", "ILLertissen", true, ""},
	{"IN", "Ingolstadt, Stadt", "Bayern", "DE-BY", "INgolstadt", false, "auslaufend – Abwicklung: Zulassungsbehörde Eichstätt"},
	{"IZ", "Steinburg", "Schleswig-Holstein", "DE-SH", "ItZehoe", true, ""},
	{"J", "Jena, Stadt", "Thüringen", "DE-TH", "Jena", false, "auslaufend – Abwicklung: Zulassungsbehörde Saale-Holzland-Kreis"},
	{"JB", "Teltow-Fläming", "Brandenburg", "DE-BB", "JüterBog", true, ""},
	{"JE", "Wittenberg", "Sachsen-Anhalt", "DE-ST", "JEssen", true, ""},
	{"JL", "Jerichower Land", "Sachsen-Anhalt", "DE-ST", "Jerichower Land", true, ""},
	{"JÜL", "Düren", "Nordrhein-Westfalen", "DE-NW", "JÜLich", true, ""},
	{"K", "Köln, Stadt", "Nordrhein-Westfalen", "DE-NW", "Köln", true, ""},
	{"KA", "Karlsruhe", "Baden-Württemberg", "DE-BW", "KArlsruhe", true, ""},
	{"KB", "Waldeck-Frankenberg", "Hessen", "DE-HE", "KorBach", true, ""},
	{"KC", "Kronach", "Bayern", "DE-BY", "KronaCh", true, ""},
	{"KE", "Kempten (Allgäu), Stadt", "Bayern", "DE-BY", "KEmpten", false, "auslaufend – Abwicklung: Zulassungsbehörde Oberallgäu"},
	{"KEH", "Kelheim", "Bayern", "DE-BY", "KElHeim", true, ""},
	{"KEL", "Ortenaukreis", "Baden-Württemberg", "DE-BW", "KEhL", true, ""},
	{"KEM", "Bayreuth / Tirschenreuth", "Bayern", "DE-BY", "KEMnath", true, ""},
	{"KF", "Kaufbeuren, Stadt", "Bayern", "DE-BY", "KauFbeuren", false, "auslaufend – Abwicklung: Zulassungsbehörde Ostallgäu"},
	{"KG", "Bad Kissingen", "Bayern", "DE-BY", "KissinGen", true, ""},
	{"KH", "Bad Kreuznach", "Rheinland-Pfalz", "DE-RP", "KreuznacH", true, ""},
	{"KI", "Kiel", "Schleswig-Holstein", "DE-SH", "KIel", true, ""},
	{"KIB", "Donnersbergkreis", "Rheinland-Pfalz", "DE-RP", "KIrchheimBolanden", true, ""},
	{"KK", "Viersen", "Nordrhein-Westfalen", "DE-NW", "Kempen, Krefeld", true, ""},
	{"KL", "Kaiserslautern", "Rheinland-Pfalz", "DE-RP", "KaisersLautern", true, ""},
	{"KLE", "Kleve", "Nordrhein-Westfalen", "DE-NW", "KLEve", true, ""},
	{"KLZ", "Altmarkkreis Salzwedel", "Sachsen-Anhalt", "DE-ST", "KLötZe", true, ""},
	{"KM", "Bautzen", "Sachsen", "DE-SN", "KaMenz", true, ""},
	{"KN", "Konstanz", "Baden-Württemberg", "DE-BW", "KoNstanz", true, ""},
	{"KO", "Koblenz, Stadt", "Rheinland-Pfalz", "DE-RP", "KOblenz", false, "auslaufend – Abwicklung: Zulassungsbehörde Mayen-Koblenz"},
	{"KR", "Krefeld, Stadt", "Nordrhein-Westfalen", "DE-NW", "KRefeld", true, ""},
	{"KRU", "Günzburg", "Bayern", "DE-BY", "KRUmbach", true, ""},
	{"KS", "Kassel", "Hessen", "DE-HE", "KasSel", true, ""},
	{"KT", "Kitzingen", "Bayern", "DE-BY", "KiTzingen", true, ""},
	{"KU", "Kulmbach", "Bayern", "DE-BY", "KUlmbach", true, ""},
	{"KUS", "Kusel", "Rheinland-Pfalz", "DE-RP", "KUSel", true, ""},
	{"KW", "Dahme-Spreewald", "Brandenburg", "DE-BB", "Königs Wusterhausen", true, ""},
	{"KY", "Ostprignitz-Ruppin", "Brandenburg", "DE-BB", "KYritz", true, ""},
	{"KYF", "Kyffhäuserkreis", "Thüringen", "DE-TH", "KYFfhäuser", true, ""},
	{"KÖN", "Rhön-Grabfeld", "Bayern", "DE-BY", "KÖNigshofen", true, ""},
	{"KÖT", "Anhalt-Bitterfeld", "Sachsen-Anhalt", "DE-ST", "KÖThen", true, ""},
	{"KÖZ", "Cham", "Bayern", "DE-BY", "KÖtZting", true, ""},
	{"KÜN", "Hohenlohekreis", "Baden-Württemberg", "DE-BW", "KÜNzelsau", true, ""},
	{"L", "Leipzig", "Sachsen", "DE-SN", "Leipzig", true, ""},
	{"LA", "Landshut", "Bayern", "DE-BY", "LAndshut", true, ""},
	{"LAN", "Dingolfing-Landau", "Bayern", "DE-BY", "LANdau", true, ""},
	{"LAU", "Nürnberger Land", "Bayern", "DE-BY", "LAUf", true, ""},
	{"LB", "Ludwigsburg", "Baden-Württemberg", "DE-BW", "LudwigsBurg", true, ""},
	{"LBS", "Saale-Orla-Kreis", "Thüringen", "DE-TH", "LoBenStein", true, ""},
	{"LBZ", "Ludwigslust-Parchim", "Mecklenburg-Vorpommern", "DE-MV", "LüBZ", true, ""},
	{"LC", "Dahme-Spreewald", "Brandenburg", "DE-BB", "LuCkau", true, ""},
	{"LD", "Landau in der Pfalz, Stadt", "Rheinland-Pfalz", "DE-RP", "LanDau", false, "auslaufend – Abwicklung: Zulassungsbehörde Kreis Südliche Weinstraße"},
	{"LDK", "Lahn-Dill-Kreis", "Hessen", "DE-HE", "Lahn-Dill-Kreis", true, ""},
	{"LDS", "Dahme-Spreewald", "Brandenburg", "DE-BB", "Landkreis Dahme-Spreewald", true, ""},
	{"LEO", "Böblingen", "Baden-Württemberg", "DE-BW", "LEOnberg", true, ""},
	{"LER", "Leer", "Niedersachsen", "DE-NI", "LEeR", true, ""},
	{"LEV", "Leverkusen, Stadt", "Nordrhein-Westfalen", "DE-NW", "LEVerkusen", true, ""},
	{"LF", "Altötting / Berchtesgadener Land / Traunstein", "Bayern", "DE-BY", "LauFen", true, ""},
	{"LG", "Lüneburg", "Niedersachsen", "DE-NI", "LüneburG", true, ""},
	{"LH", "Coesfeld / Unna", "Nordrhein-Westfalen", "DE-NW", "LüdingHausen", true, ""},
	{"LI", "Lindau (Bodensee)", "Bayern", "DE-BY", "LIndau", true, ""},
	{"LIB", "Elbe-Elster", "Brandenburg", "DE-BB", "LIeBenwerda", true, ""},
	{"LIF", "Lichtenfels", "Bayern", "DE-BY", "LIchtenFels", true, ""},
	{"LIP", "Lippe", "Nordrhein-Westfalen", "DE-NW", "LIPpe", true, ""},
	{"LK", "Minden-Lübbecke", "Nordrhein-Westfalen", "DE-NW", "LübcKe", true, ""},
	{"LL", "Landsberg am Lech", "Bayern", "DE-BY", "Landsberg am Lech", true, ""},
	{"LM", "Limburg-Weilburg", "Hessen", "DE-HE", "LiMburg", true, ""},
	{"LN", "Dahme-Spreewald", "Brandenburg", "DE-BB", "LübbeN", true, ""},
	{"LOS", "Oder-Spree", "Brandenburg", "DE-BB", "Landkreis Oder-Spree", true, ""},
	{"LP", "Soest", "Nordrhein-Westfalen", "DE-NW", "LiPpstadt", true, ""},
	{"LR", "Ortenaukreis", "Baden-Württemberg", "DE-BW", "LahR", true, ""},
	{"LRO", "Rostock, Landkreis", "Mecklenburg-Vorpommern", "DE-MV", "Landkreis ROstock", true, ""},
	{"LSZ", "Unstrut-Hainich-Kreis", "Thüringen", "DE-TH", "LangenSalZa", true, ""},
	{"LU", "Ludwigshafen am Rhein", "Rheinland-Pfalz", "DE-RP", "LUdwigshafen", false, "auslaufend – Abwicklung: Zulassungsbehörde Rhein-Pfalz-Kreis"},
	{"LUK", "Teltow-Fläming", "Brandenburg", "DE-BB", "LUcKenwalde", true, ""},
	{"LUP", "Ludwigslust-Parchim", "Mecklenburg-Vorpommern", "DE-MV", "LUdwigslust, Parchim", true, ""},
	{"LWL", "Ludwigslust-Parchim", "Mecklenburg-Vorpommern", "DE-MV", "LudWigsLust", true, ""},
	{"LÖ", "Lörrach", "Baden-Württemberg", "DE-BW", "LÖrrach", true, ""},
	{"LÖB", "Görlitz", "Sachsen", "DE-SN", "LÖBau", true, ""},
	{"LÜN", "Unna", "Nordrhein-Westfalen", "DE-NW", "LÜNen", true, ""},
	{"M", "München", "Bayern", "DE-BY", "München", true, ""},
	{"MA", "Mannheim, Stadt", "Baden-Württemberg", "DE-BW", "MAnnheim", false, "auslaufend – Abwicklung: Zulassungsbehörde Rhein-Neckar-Kreis"},
	{"MAB", "Erzgebirgskreis", "Sachsen", "DE-SN", "MArienBerg", true, ""},
	{"MAI", "Kelheim / Landshut", "Bayern", "DE-BY", "MAInburg", true, ""},
	{"MAK", "Wunsiedel i. Fichtelgebirge", "Bayern", "DE-BY", "MArKtredwitz", true, ""},
	{"MAL", "Landshut / Straubing-Bogen", "Bayern", "DE-BY", "MALlersdorf", true, ""},
	{"MB", "Miesbach", "Bayern", "DE-BY", "MiesBach", true, ""},
	{"MC", "Mecklenburgische Seenplatte", "Mecklenburg-Vorpommern", "DE-MV", "MalChin", true, ""},
	{"MD", "Magdeburg, Stadt", "Sachsen-Anhalt", "DE-ST", "MagDeburg", true, ""},
	{"ME", "Mettmann", "Nordrhein-Westfalen", "DE-NW", "MEttmann", true, ""},
	{"MED", "Dithmarschen", "Schleswig-Holstein", "DE-SH", "MElDorf", true, ""},
	{"MEG", "Schwalm-Eder-Kreis", "Hessen", "DE-HE", "MElsunGen", true, ""},
	{"MEI", "Meißen", "Sachsen", "DE-SN", "MEIßen", true, ""},
	{"MEK", "Erzgebirgskreis", "Sachsen", "DE-SN", "Mittlerer ErzgebirgsKreis", true, ""},
	{"MEL", "Osnabrück", "Niedersachsen", "DE-NI", "MELle", true, ""},
	{"MER", "Saalekreis", "Sachsen-Anhalt", "DE-ST", "MERseburg", true, ""},
	{"MET", "Rhön-Grabfeld", "Bayern", "DE-BY", "MEllrichstadT", true, ""},
	{"MG", "Mönchengladbach, Stadt", "Nordrhein-Westfalen", "DE-NW", "MönchenGladbach", true, ""},
	{"MGH", "Main-Tauber-Kreis", "Baden-Württemberg", "DE-BW", "MerGentHeim", true, ""},
	{"MGN", "Schmalkalden-Meiningen", "Thüringen", "DE-TH", "MeininGeN", true, ""},
	{"MH", "Mülheim an der Ruhr, Stadt", "Nordrhein-Westfalen", "DE-NW", "MülHeim", true, ""},
	{"MHL", "Unstrut-Hainich-Kreis", "Thüringen", "DE-TH", "MüHLhausen", true, ""},
	{"MI", "Minden-Lübbecke", "Nordrhein-Westfalen", "DE-NW", "MInden", true, ""},
	{"MIL", "Miltenberg", "Bayern", "DE-BY", "MILtenberg", true, ""},
	{"MK", "Märkischer Kreis", "Nordrhein-Westfalen", "DE-NW", "Märkischer Kreis", true, ""},
	{"MKK", "Main-Kinzig-Kreis", "Hessen", "DE-HE", "Main-Kinzig-Kreis", true, ""},
	{"ML", "Mansfeld-Südharz", "Sachsen-Anhalt", "DE-ST", "Mansfelder Land", true, ""},
	{"MM", "Memmingen, Stadt", "Bayern", "DE-BY", "MemMingen", false, "auslaufend – Abwicklung: Zulassungsbehörde Unterallgäu"},
	{"MN", "Unterallgäu", "Bayern", "DE-BY", "MiNdelheim", true, ""},
	{"MO", "Wesel", "Nordrhein-Westfalen", "DE-NW", "MOers", true, ""},
	{"MOD", "Ostallgäu", "Bayern", "DE-BY", "MarktOberDorf", true, ""},
	{"MOL", "Märkisch-Oderland", "Brandenburg", "DE-BB", "Märkisch-OderLand", true, ""},
	{"MON", "Aachen / Düren", "Nordrhein-Westfalen", "DE-NW", "MONschau", true, ""},
	{"MOS", "Neckar-Odenwald-Kreis", "Baden-Württemberg", "DE-BW", "MOSbach", true, ""},
	{"MQ", "Saalekreis", "Sachsen-Anhalt", "DE-ST", "Merseburg, Querfurt", true, ""},
	{"MR", "Marburg-Biedenkopf", "Hessen", "DE-HE", "MaRburg", true, ""},
	{"MS", "Münster, Stadt", "Nordrhein-Westfalen", "DE-NW", "MünSter", true, ""},
	{"MSE", "Mecklenburgische Seenplatte", "Mecklenburg-Vorpommern", "DE-MV", "Mecklenburgische SEenplatte", true, ""},
	{"MSH", "Mansfeld-Südharz", "Sachsen-Anhalt", "DE-ST", "Mansfeld, SüdHarz", true, ""},
	{"MSP", "Main-Spessart", "Bayern", "DE-BY", "Main, SPessart", true, ""},
	{"MST", "Mecklenburgische Seenplatte", "Mecklenburg-Vorpommern", "DE-MV", "Mecklenburg-STrelitz", true, ""},
	{"MTK", "Main-Taunus-Kreis", "Hessen", "DE-HE", "Main-Taunus-Kreis", true, ""},
	{"MTL", "Leipzig", "Sachsen", "DE-SN", "MuldenTaL", true, ""},
	{"MU", "Landkreis München", "Bayern", "DE-BY", "Münchner Umland", true, ""},
	{"MUC", "München, Stadt", "Bayern", "DE-BY", "MUenChen", true, ""},
	{"MW", "Mittelsachsen", "Sachsen", "DE-SN", "MittWeida", true, ""},
	{"MY", "Mayen-Koblenz", "Rheinland-Pfalz", "DE-RP", "MaYen", true, ""},
	{"MYK", "Mayen-Koblenz", "Rheinland-Pfalz", "DE-RP", "MaYen, Koblenz", true, ""},
	{"MZ", "Mainz", "Rheinland-Pfalz", "DE-RP", "MainZ", true, ""},
	{"MZG", "Merzig-Wadern", "Saarland", "DE-SL", "MerZiG", true, ""},
	{"MÜ", "Mühldorf am Inn", "Bayern", "DE-BY", "MÜhldorf", true, ""},
	{"MÜB", "Bayreuth / Hof", "Bayern", "DE-BY", "MÜnchBerg", true, ""},
	{"MÜL", "Breisgau-Hochschwarzwald", "Baden-Württemberg", "DE-BW", "MÜLlheim", true, ""},
	{"MÜR", "Mecklenburgische Seenplatte", "Mecklenburg-Vorpommern", "DE-MV", "MÜRitz", true, ""},
	{"N", "Nürnberg Stadt / Nürnberger Land", "Bayern", "DE-BY", "Nürnberg", true, ""},
	{"NAB", "Amberg-Sulzbach / Schwandorf", "Bayern", "DE-BY", "NABburg", true, ""},
	{"NAI", "Hof", "Bayern", "DE-BY", "NAIla", true, ""},
	{"NAU", "Havelland", "Brandenburg", "DE-BB", "NAUen", true, ""},
	{"NB", "Neubrandenburg, Stadt", "Mecklenburg-Vorpommern", "DE-MV", "NeuBrandenburg", false, "auslaufend – Abwicklung: Zulassungsbehörde Mecklenburg-Strelitz"},
	{"ND", "Neuburg-Schrobenhausen", "Bayern", "DE-BY", "Neuburg an der Donau", true, ""},
	{"NDH", "Nordhausen", "Thüringen", "DE-TH", "NorDHausen", true, ""},
	{"NE", "Rhein-Kreis Neuss", "Nordrhein-Westfalen", "DE-NW", "NEuss", true, ""},
	{"NEA", "Neustadt an der Aisch-Bad Windsheim", "Bayern", "DE-BY", "NEustadt an der Aisch", true, ""},
	{"NEB", "Burgenlandkreis", "Sachsen-Anhalt", "DE-ST", "NEBra", true, ""},
	{"NEC", "Zulassungsstelle Coburg, Zweckverband", "Bayern", "DE-BY", "NEustadt bei Coburg", true, ""},
	{"NEN", "Schwandorf", "Bayern", "DE-BY", "NEuNburg", true, ""},
	{"NES", "Rhön-Grabfeld", "Bayern", "DE-BY", "NEustadt an der Saale", true, ""},
	{"NEU", "Breisgau-Hochschwarzwald", "Baden-Württemberg", "DE-BW", "NEUstadt", true, ""},
	{"NEW", "Neustadt an der Waldnaab", "Bayern", "DE-BY", "NEustadt an der Waldnaab", true, ""},
	{"NF", "Nordfriesland", "Schleswig-Holstein", "DE-SH", "NordFriesland", true, ""},
	{"NH", "Sonneberg", "Thüringen", "DE-TH", "NeuHaus", true, ""},
	{"NI", "Nienburg (Weser)", "Niedersachsen", "DE-NI", "NIenburg", true, ""},
	{"NK", "Neunkirchen Saar", "Saarland", "DE-SL", "NeunKirchen", true, ""},
	{"NM", "Neumarkt in der Oberpfalz", "Bayern", "DE-BY", "NeuMarkt", true, ""},
	{"NMB", "Burgenlandkreis", "Sachsen-Anhalt", "DE-ST", "NauMBurg", true, ""},
	{"NMS", "Neumünster", "Schleswig-Holstein", "DE-SH", "NeuMünSter", true, ""},
	{"NOH", "Grafschaft Bentheim", "Niedersachsen", "DE-NI", "NOrdHorn", true, ""},
	{"NOL", "Görlitz", "Sachsen", "DE-SN", "Niederschlesische OberLausitz", true, ""},
	{"NOM", "Northeim", "Niedersachsen", "DE-NI", "NOrtheiM", true, ""},
	{"NOR", "Aurich", "Niedersachsen", "DE-NI", "NORden", true, ""},
	{"NP", "Ostprignitz-Ruppin", "Brandenburg", "DE-BB", "NeurupPin", true, ""},
	{"NR", "Neuwied", "Rheinland-Pfalz", "DE-RP", "Neuwied am Rhein", true, ""},
	{"NT", "Esslingen", "Baden-Württemberg", "DE-BW", "NürTingen", true, ""},
	{"NU", "Neu-Ulm", "Bayern", "DE-BY", "Neu-Ulm", true, ""},
	{"NVP", "Vorpommern-Rügen", "Mecklenburg-Vorpommern", "DE-MV", "NordVorPommern", true, ""},
	{"NW", "Neustadt an der Weinstraße", "Rheinland-Pfalz", "DE-RP", "Neustadt an der Weinstraße", false, "auslaufend – Abwicklung: Zulassungsbehörde Bad Dürkheim"},
	{"NWM", "Nordwestmecklenburg", "Mecklenburg-Vorpommern", "DE-MV", "NordWestMecklenburg", true, ""},
	{"NY", "Görlitz", "Sachsen", "DE-SN", "NieskY", true, ""},
	{"NZ", "Mecklenburgische Seenplatte", "Mecklenburg-Vorpommern", "DE-MV", "NeustrelitZ", true, ""},
	{"NÖ", "Donau-Ries", "Bayern", "DE-BY", "NÖrdlingen", true, ""},
	{"OA", "Oberallgäu", "Bayern", "DE-BY", "OberAllgäu", true, ""},
	{"OAL", "Ostallgäu", "Bayern", "DE-BY", "OstALlgäu", true, ""},
	{"OB", "Oberhausen, Stadt", "Nordrhein-Westfalen", "DE-NW", "OBerhausen", true, ""},
	{"OBB", "Miltenberg", "Bayern", "DE-BY", "OBernBurg", true, ""},
	{"OBG", "Stendal", "Sachsen-Anhalt", "DE-ST", "OsterBurG", true, ""},
	{"OC", "Börde", "Sachsen-Anhalt", "DE-ST", "OsChersleben", true, ""},
	{"OCH", "Würzburg", "Bayern", "DE-BY", "OCHsenfurt", true, ""},
	{"OD", "Stormarn", "Schleswig-Holstein", "DE-SH", "OlDesloe", true, ""},
	{"OE", "Olpe", "Nordrhein-Westfalen", "DE-NW", "OlpE", true, ""},
	{"OF", "Offenbach am Main", "Hessen", "DE-HE", "OFfenbach", true, ""},
	{"OG", "Ortenaukreis", "Baden-Württemberg", "DE-BW", "OffenburG", true, ""},
	{"OH", "Ostholstein", "Schleswig-Holstein", "DE-SH", "OstHolstein", true, ""},
	{"OHA", "Göttingen", "Niedersachsen", "DE-NI", "Osterode am HArz", true, ""},
	{"OHV", "Oberhavel", "Brandenburg", "DE-BB", "OberHaVel", true, ""},
	{"OHZ", "Osterholz", "Niedersachsen", "DE-NI", "OsterHolZ", true, ""},
	{"OK", "Börde", "Sachsen-Anhalt", "DE-ST", "OhreKreis", true, ""},
	{"OL", "Oldenburg (Oldenburg)", "Niedersachsen", "DE-NI", "OLdenburg", true, ""},
	{"OP", "Leverkusen, Stadt", "Nordrhein-Westfalen", "DE-NW", "OPladen", true, ""},
	{"OPR", "Ostprignitz-Ruppin", "Brandenburg", "DE-BB", "OstPrignitz, Ruppin", true, ""},
	{"OS", "Osnabrück", "Niedersachsen", "DE-NI", "OSnabrück", true, ""},
	{"OSL", "Oberspreewald-Lausitz", "Brandenburg", "DE-BB", "OberSpreewald, Lausitz", true, ""},
	{"OTW", "Neunkirchen", "Saarland", "DE-SL", "OTtWeiler", true, ""},
	{"OVI", "Schwandorf", "Bayern", "DE-BY", "OberVIechtach", true, ""},
	{"OVL", "Vogtlandkreis", "Sachsen", "DE-SN", "OberVogtLand", true, ""},
	{"OVP", "Vorpommern-Greifswald", "Mecklenburg-Vorpommern", "DE-MV", "OstVorPommern", true, ""},
	{"OZ", "Nordsachsen", "Sachsen", "DE-SN", "OschatZ", true, ""},
	{"P", "Potsdam, Stadt", "Brandenburg", "DE-BB", "Potsdam", false, "auslaufend – Abwicklung: Zulassungsbehörde Potsdam-Mittelmark"},
	{"PA", "Passau", "Bayern", "DE-BY", "PAssau", true, ""},
	{"PAF", "Pfaffenhofen a. d. Ilm", "Bayern", "DE-BY", "PfAFfenhofen", true, ""},
	{"PAN", "Rottal-Inn", "Bayern", "DE-BY", "PfArrkircheN", true, ""},
	{"PAR", "Kelheim / Neumarkt i. d. Opf.", "Bayern", "DE-BY", "PARsberg", true, ""},
	{"PB", "Paderborn", "Nordrhein-Westfalen", "DE-NW", "PaderBorn", true, ""},
	{"PCH", "Ludwigslust-Parchim", "Mecklenburg-Vorpommern", "DE-MV", "ParCHim", true, ""},
	{"PE", "Peine", "Niedersachsen", "DE-NI", "PEine", true, ""},
	{"PEG", "Bayreuth / Forchheim / Nürnberger Land", "Bayern", "DE-BY", "PEGnitz", true, ""},
	{"PF", "Pforzheim, Stadt / Enzkreis", "Baden-Württemberg", "DE-BW", "PForzheim", true, ""},
	{"PI", "Pinneberg", "Schleswig-Holstein", "DE-SH", "PInneberg", true, ""},
	{"PIR", "Sächsische Schweiz-Osterzgebirge", "Sachsen", "DE-SN", "PIRna", true, ""},
	{"PL", "Vogtlandkreis", "Sachsen", "DE-SN", "PLauen", true, ""},
	{"PLÖ", "Plön", "Schleswig-Holstein", "DE-SH", "PLÖn", true, ""},
	{"PM", "Potsdam-Mittelmark", "Brandenburg", "DE-BB", "Potsdam, Mittelmark", true, ""},
	{"PN", "Saale-Orla-Kreis", "Thüringen", "DE-TH", "PößNeck", true, ""},
	{"PR", "Prignitz", "Brandenburg", "DE-BB", "PRignitz", true, ""},
	{"PRÜ", "Eifelkreis Bitburg-Prüm", "Rheinland-Pfalz", "DE-RP", "PRÜm", true, ""},
	{"PS", "Pirmasens, Stadt / Südwestpfalz", "Rheinland-Pfalz", "DE-RP", "PirmaSens", true, ""},
	{"PW", "Vorpommern-Greifswald", "Mecklenburg-Vorpommern", "DE-MV", "PaseWalk", true, ""},
	{"PZ", "Uckermark", "Brandenburg", "DE-BB", "PrenZlau", true, ""},
	{"QFT", "Saalekreis", "Sachsen-Anhalt", "DE-ST", "QuerFurT", true, ""},
	{"QLB", "Harz", "Sachsen-Anhalt", "DE-ST", "QuedLinBurg", true, ""},
	{"R", "Regensburg", "Bayern", "DE-BY", "Regensburg", true, ""},
	{"RA", "Rastatt", "Baden-Württemberg", "DE-BW", "RAstatt", true, ""},
	{"RC", "Vogtlandkreis", "Sachsen", "DE-SN", "ReiChenbach", true, ""},
	{"RD", "Rendsburg-Eckernförde", "Schleswig-Holstein", "DE-SH", "RenDsburg", true, ""},
	{"RDG", "Vorpommern-Rügen", "Mecklenburg-Vorpommern", "DE-MV", "Ribnitz-DamGarten", true, ""},
	{"RE", "Recklinghausen", "Nordrhein-Westfalen", "DE-NW", "REcklinghausen", true, ""},
	{"REG", "Regen", "Bayern", "DE-BY", "REGen", true, ""},
	{"REH", "Hof / Wunsiedel im Fichtelgebirge", "Bayern", "DE-BY", "REHau", true, ""},
	{"REI", "Berchtesgadener Land", "Bayern", "DE-BY", "REIchenhall", true, ""},
	{"RG", "Meißen", "Sachsen", "DE-SN", "Riesa, Großenhain", true, ""},
	{"RH", "Roth", "Bayern", "DE-BY", "RotH", true, ""},
	{"RI", "Schaumburg", "Niedersachsen", "DE-NI", "RInteln", true, ""},
	{"RID", "Kelheim", "Bayern", "DE-BY", "RIeDenburg", true, ""},
	{"RIE", "Meißen", "Sachsen", "DE-SN", "RIEsa", true, ""},
	{"RL", "Mittelsachsen", "Sachsen", "DE-SN", "RochLitz", true, ""},
	{"RM", "Mecklenburgische Seenplatte", "Mecklenburg-Vorpommern", "DE-MV", "Röbel/Müritz", true, ""},
	{"RN", "Havelland", "Brandenburg", "DE-BB", "RatheNow", true, ""},
	{"RO", "Rosenheim", "Bayern", "DE-BY", "ROsenheim", true, ""},
	{"ROD", "Cham / Schwandorf", "Bayern", "DE-BY", "RODing", true, ""},
	{"ROF", "Hersfeld-Rotenburg", "Hessen", "DE-HE", "ROtenburg an der Fulda", true, ""},
	{"ROK", "Donnersbergkreis", "Rheinland-Pfalz", "DE-RP", "ROcKenhausen", true, ""},
	{"ROL", "Kelheim / Landshut", "Bayern", "DE-BY", "ROttenburg an der Laaber", true, ""},
	{"ROS", "Rostock, Landkreis", "Mecklenburg-Vorpommern", "DE-MV", "ROStock", true, ""},
	{"ROT", "Ansbach", "Bayern", "DE-BY", "ROthenburg ob der Tauber", true, ""},
	{"ROW", "Rotenburg (Wümme)", "Niedersachsen", "DE-NI", "ROtenburg (Wümme)", true, ""},
	{"RP", "Rhein-Pfalz-Kreis", "Rheinland-Pfalz", "DE-RP", "Rhein-Pfalz", true, ""},
	{"RS", "Remscheid, Stadt", "Nordrhein-Westfalen", "DE-NW", "RemScheid", true, ""},
	{"RSL", "Dessau-Roßlau, Stadt", "Sachsen-Anhalt", "DE-ST", "RosSLau", true, ""},
	{"RT", "Reutlingen", "Baden-Württemberg", "DE-BW", "ReuTlingen", true, ""},
	{"RU", "Saalfeld-Rudolstadt", "Thüringen", "DE-TH", "RUdolstadt", true, ""},
	{"RV", "Ravensburg", "Baden-Württemberg", "DE-BW", "RaVensburg", true, ""},
	{"RW", "Rottweil", "Baden-Württemberg", "DE-BW", "RottWeil", true, ""},
	{"RZ", "Herzogtum Lauenburg", "Schleswig-Holstein", "DE-SH", "RatZeburg", true, ""},
	{"RÜD", "Rheingau-Taunus-Kreis", "Hessen", "DE-HE", "RÜDesheim", true, ""},
	{"RÜG", "Vorpommern-Rügen", "Mecklenburg-Vorpommern", "DE-MV", "RÜGen", true, ""},
	{"S", "Stuttgart, Stadt", "Baden-Württemberg", "DE-BW", "Stuttgart", true, ""},
	{"SAB", "Trier-Saarburg", "Rheinland-Pfalz", "DE-RP", "SAarBurg", true, ""},
	{"SAD", "Schwandorf", "Bayern", "DE-BY", "SchwAnDorf", true, ""},
	{"SAN", "Hof / Kronach / Kulmbach", "Bayern", "DE-BY", "StAdtsteiNach", true, ""},
	{"SAW", "Altmarkkreis Salzwedel", "Sachsen-Anhalt", "DE-ST", "SAlzWedel", true, ""},
	{"SB", "Saarbrücken, Stadt und Stadtverband", "Saarland", "DE-SL", "SaarBrücken", true, ""},
	{"SBG", "Vorpommern-Greifswald", "Mecklenburg-Vorpommern", "DE-MV", "StrasBurG", true, ""},
	{"SBK", "Salzlandkreis", "Sachsen-Anhalt", "DE-ST", "SchöneBecK", true, ""},
	{"SC", "Schwabach, Stadt", "Bayern", "DE-BY", "SChwabach", false, "auslaufend – Abwicklung: Zulassungsbehörde Roth"},
	{"SCZ", "Saale-Orla-Kreis", "Thüringen", "DE-TH", "SChleiZ", true, ""},
	{"SDH", "Kyffhäuserkreis", "Thüringen", "DE-TH", "SonDersHausen", true, ""},
	{"SDL", "Stendal", "Sachsen-Anhalt", "DE-ST", "StenDaL", true, ""},
	{"SDT", "Uckermark", "Brandenburg", "DE-BB", "SchweDT", true, ""},
	{"SE", "Segeberg", "Schleswig-Holstein", "DE-SH", "SEgeberg", true, ""},
	{"SEB", "Sächsische Schweiz-Osterzgebirge", "Sachsen", "DE-SN", "SEBnitz", true, ""},
	{"SEE", "Märkisch-Oderland", "Brandenburg", "DE-BB", "SEElow", true, ""},
	{"SEF", "Neustadt a. d. Aisch-Bad Windsheim", "Bayern", "DE-BY", "SchEinFeld", true, ""},
	{"SEL", "Wunsiedel i. Fichtelgebirge", "Bayern", "DE-BY", "SELb", true, ""},
	{"SFB", "Oberspreewald-Lausitz", "Brandenburg", "DE-BB", "SenFtenBerg", true, ""},
	{"SFT", "Salzlandkreis", "Sachsen-Anhalt", "DE-ST", "StaßFurT", true, ""},
	{"SG", "Solingen, Stadt", "Nordrhein-Westfalen", "DE-NW", "SolinGen", true, ""},
	{"SGH", "Mansfeld-Südharz", "Sachsen-Anhalt", "DE-ST", "SanGerHausen", true, ""},
	{"SHA", "Schwäbisch Hall", "Baden-Württemberg", "DE-BW", "Schwäbisch HAll", true, ""},
	{"SHG", "Schaumburg", "Niedersachsen", "DE-NI", "StadtHaGen", true, ""},
	{"SHK", "Saale-Holzland-Kreis", "Thüringen", "DE-TH", "Saale-Holzland-Kreis", true, ""},
	{"SHL", "Suhl, Stadt", "Thüringen", "DE-TH", "SuHL", false, "auslaufend – Abwicklung: Zulassungsbehörde Hildburghausen"},
	{"SI", "Siegen-Wittgenstein", "Nordrhein-Westfalen", "DE-NW", "SIegen", true, ""},
	{"SIG", "Sigmaringen", "Baden-Württemberg", "DE-BW", "SIGmaringen", true, ""},
	{"SIM", "Rhein-Hunsrück-Kreis", "Rheinland-Pfalz", "DE-RP", "SIMmern", true, ""},
	{"SK", "Saalekreis", "Sachsen-Anhalt", "DE-ST", "SaaleKreis", true, ""},
	{"SL", "Schleswig-Flensburg", "Schleswig-Holstein", "DE-SH", "SchLeswig", true, ""},
	{"SLE", "Düren / Euskirchen", "Nordrhein-Westfalen", "DE-NW", "SchLEiden", true, ""},
	{"SLF", "Saalfeld-Rudolstadt", "Thüringen", "DE-TH", "SaaLFeld", true, ""},
	{"SLG", "Ravensburg / Sigmaringen", "Baden-Württemberg", "DE-BW", "SauLGau", true, ""},
	{"SLK", "Salzlandkreis", "Sachsen-Anhalt", "DE-ST", "SalzLandKreis", true, ""},
	{"SLN", "Altenburger Land", "Thüringen", "DE-TH", "SchmölLN", true, ""},
	{"SLS", "Saarlouis", "Saarland", "DE-SL", "SaarLouiS", true, ""},
	{"SLZ", "Wartburgkreis", "Thüringen", "DE-TH", "SaLZungen", true, ""},
	{"SLÜ", "Main-Kinzig-Kreis", "Hessen", "DE-HE", "SchLÜchtern", true, ""},
	{"SM", "Schmalkalden-Meiningen", "Thüringen", "DE-TH", "SchMalkalden", true, ""},
	{"SMÜ", "Augsburg", "Bayern", "DE-BY", "SchwabMÜnchen", true, ""},
	{"SN", "Schwerin, Stadt", "Mecklenburg-Vorpommern", "DE-MV", "SchweriN", false, "auslaufend – Abwicklung: Zulassungsbehörde Ludwigslust-Parchim"},
	{"SO", "Soest", "Nordrhein-Westfalen", "DE-NW", "SOest", true, ""},
	{"SOB", "Neuburg-Schrobenhausen", "Bayern", "DE-BY", "SchrOBenhausen", true, ""},
	{"SOG", "Weilheim-Schongau", "Bayern", "DE-BY", "SchOnGau", true, ""},
	{"SOK", "Saale-Orla-Kreis", "Thüringen", "DE-TH", "Saale-Orla-Kreis", true, ""},
	{"SON", "Sonneberg", "Thüringen", "DE-TH", "SONneberg", true, ""},
	{"SP", "Speyer, Stadt", "Rheinland-Pfalz", "DE-RP", "SPeyer", false, "auslaufend – Abwicklung: Zulassungsbehörde Rhein-Pfalz-Kreis"},
	{"SPB", "Spree-Neiße", "Brandenburg", "DE-BB", "SPremBerg", true, ""},
	{"SPN", "Spree-Neiße", "Brandenburg", "DE-BB", "SPree, Neiße", true, ""},
	{"SR", "Straubing / Straubing-Bogen", "Bayern", "DE-BY", "StRaubing", true, ""},
	{"SRB", "Märkisch-Oderland", "Brandenburg", "DE-BB", "StRausBerg", true, ""},
	{"SRO", "Saale-Holzland-Kreis", "Thüringen", "DE-TH", "StadtROda", true, ""},
	{"ST", "Steinfurt", "Nordrhein-Westfalen", "DE-NW", "STeinfurt", true, ""},
	{"STA", "Starnberg", "Bayern", "DE-BY", "STArnberg", true, ""},
	{"STB", "Ludwigslust-Parchim", "Mecklenburg-Vorpommern", "DE-MV", "STernBerg", true, ""},
	{"STD", "Stade", "Niedersachsen", "DE-NI", "STaDe", true, ""},
	{"STE", "Lichtenfels", "Bayern", "DE-BY", "STaffelstEin", true, ""},
	{"STL", "Erzgebirgskreis", "Sachsen", "DE-SN", "STolLberg", true, ""},
	{"STO", "Konstanz / Sigmaringen", "Baden-Württemberg", "DE-BW", "STOckach", true, ""},
	{"SU", "Rhein-Sieg-Kreis", "Nordrhein-Westfalen", "DE-NW", "SiegbUrg", true, ""},
	{"SUL", "Amberg-Sulzbach", "Bayern", "DE-BY", "SULzbach-Rosenberg", true, ""},
	{"SW", "Schweinfurt", "Bayern", "DE-BY", "SchWeinfurt", true, ""},
	{"SWA", "Rheingau-Taunus-Kreis", "Hessen", "DE-HE", "SchWAlbach", true, ""},
	{"SY", "Diepholz", "Niedersachsen", "DE-NI", "SYke", true, ""},
	{"SZ", "Salzgitter, Stadt", "Niedersachsen", "DE-NI", "SalZgitter", true, ""},
	{"SZB", "Erzgebirgskreis", "Sachsen", "DE-SN", "SchwarZenBerg", true, ""},
	{"SÄK", "Waldshut", "Baden-Württemberg", "DE-BW", "SÄcKingen", true, ""},
	{"SÖM", "Sömmerda", "Thüringen", "DE-TH", "SÖMmerda", true, ""},
	{"SÜW", "Südliche Weinstraße", "Rheinland-Pfalz", "DE-RP", "SÜdliche Weinstraße", true, ""},
	{"TBB", "Main-Tauber-Kreis", "Baden-Württemberg", "DE-BW", "TauBerBischofsheim", true, ""},
	{"TDO", "Nordsachsen", "Sachsen", "DE-SN", "Torgau, Delitzsch, Oschatz", true, ""},
	{"TE", "Steinfurt", "Nordrhein-Westfalen", "DE-NW", "TEcklenburg", true, ""},
	{"TET", "Rostock, Landkreis", "Mecklenburg-Vorpommern", "DE-MV", "TETerow", true, ""},
	{"TF", "Teltow-Fläming", "Brandenburg", "DE-BB", "Teltow, Fläming", true, ""},
	{"TG", "Nordsachsen", "Sachsen", "DE-SN", "TorGau", true, ""},
	{"TIR", "Tirschenreuth", "Bayern", "DE-BY", "TIRschenreuth", true, ""},
	{"TO", "Nordsachsen", "Sachsen", "DE-SN", "Torgau, Oschatz", true, ""},
	{"TP", "Uckermark", "Brandenburg", "DE-BB", "TemPlin", true, ""},
	{"TR", "Trier, Stadt und Trier-Saarburg", "Rheinland-Pfalz", "DE-RP", "TRier", true, ""},
	{"TS", "Traunstein", "Bayern", "DE-BY", "TraunStein", true, ""},
	{"TT", "Bodenseekreis", "Baden-Württemberg", "DE-BW", "TeTtnang", true, ""},
	{"TUT", "Tuttlingen", "Baden-Württemberg", "DE-BW", "TUTtlingen", true, ""},
	{"TÖL", "Bad Tölz-Wolfratshausen", "Bayern", "DE-BY", "TÖLz", true, ""},
	{"TÜ", "Tübingen", "Baden-Württemberg", "DE-BW", "TÜbingen", true, ""},
	{"UE", "Uelzen", "Niedersachsen", "DE-NI", "UElzen", true, ""},
	{"UEM", "Vorpommern-Greifswald", "Mecklenburg-Vorpommern", "DE-MV", "UEckerMünde", true, ""},
	{"UER", "Vorpommern-Greifswald", "Mecklenburg-Vorpommern", "DE-MV", "UEcker-Randow", true, ""},
	{"UFF", "Neustadt a. d. Aisch-Bad Windsheim", "Bayern", "DE-BY", "UFFenheim", true, ""},
	{"UH", "Unstrut-Hainich-Kreis", "Thüringen", "DE-TH", "Unstrut, Hainich", true, ""},
	{"UL", "Ulm, Stadt / Alb-Donau-Kreis", "Baden-Württemberg", "DE-BW", "ULm", true, ""},
	{"UM", "Uckermark", "Brandenburg", "DE-BB", "UckerMark", true, ""},
	{"UN", "Unna", "Nordrhein-Westfalen", "DE-NW", "UNna", true, ""},
	{"USI", "Hochtaunuskreis", "Hessen", "DE-HE", "USIngen", true, ""},
	{"V", "Vogtlandkreis", "Sachsen", "DE-SN", "Vogtland", true, ""},
	{"VAI", "Ludwigsburg", "Baden-Württemberg", "DE-BW", "VAIhingen", true, ""},
	{"VB", "Vogelsbergkreis", "Hessen", "DE-HE", "VogelsBerg", true, ""},
	{"VEC", "Vechta", "Niedersachsen", "DE-NI", "VEChta", true, ""},
	{"VER", "Verden", "Niedersachsen", "DE-NI", "VERden", true, ""},
	{"VG", "Vorpommern-Greifswald", "Mecklenburg-Vorpommern", "DE-MV", "Vorpommern, Greifswald", true, ""},
	{"VIB", "Landshut / Rottal-Inn", "Bayern", "DE-BY", "VIlsBiburg", true, ""},
	{"VIE", "Viersen", "Nordrhein-Westfalen", "DE-NW", "VIErsen", true, ""},
	{"VIT", "Regen", "Bayern", "DE-BY", "VIechTach", true, ""},
	{"VK", "Völklingen, Stadt", "Saarland", "DE-SL", "VölKlingen", true, ""},
	{"VOH", "Neustadt a. d. Waldnaab", "Bayern", "DE-BY", "VOHenstrauß", true, ""},
	{"VR", "Vorpommern-Rügen", "Mecklenburg-Vorpommern", "DE-MV", "Vorpommern, Rügen", true, ""},
	{"VS", "Schwarzwald-Baar-Kreis", "Baden-Württemberg", "DE-BW", "Villingen-Schwenningen", true, ""},
	{"W", "Wuppertal, Stadt", "Nordrhein-Westfalen", "DE-NW", "Wuppertal", true, ""},
	{"WA", "Waldeck-Frankenberg", "Hessen", "DE-HE", "WAldeck", true, ""},
	{"WAF", "Warendorf", "Nordrhein-Westfalen", "DE-NW", "WArendorF", true, ""},
	{"WAK", "Wartburgkreis", "Thüringen", "DE-TH", "WArtburgKreis", true, ""},
	{"WAN", "Herne, Stadt", "Nordrhein-Westfalen", "DE-NW", "WANne", true, ""},
	{"WAR", "Höxter", "Nordrhein-Westfalen", "DE-NW", "WARburg", true, ""},
	{"WAT", "Bochum, Stadt", "Nordrhein-Westfalen", "DE-NW", "WATtenscheid", true, ""},
	{"WB", "Wittenberg", "Sachsen-Anhalt", "DE-ST", "WittenBerg", true, ""},
	{"WBG", "Wolfsburg, Stadt", "Niedersachsen", "DE-NI", "WorBiS", true, ""},
	{"WBS", "Eichsfeld", "Thüringen", "DE-TH", "WerDAu", true, ""},
	{"WDA", "Zwickau", "Sachsen", "DE-SN", "WEimar", true, ""},
	{"WE", "Weimar, Stadt", "Thüringen", "DE-TH", "WEimar", false, "auslaufend – Abwicklung: Zulassungsbehörde Weimarer Land"},
	{"WEL", "Limburg-Weilburg", "Hessen", "DE-HE", "WEilburg", true, ""},
	{"WEN", "Weiden in der Oberpfalz, Stadt", "Bayern", "DE-BY", "WEideN", true, ""},
	{"WER", "Augsburg / Dillingen a. d. Donau", "Bayern", "DE-BY", "WERtingen", true, ""},
	{"WES", "Wesel", "Nordrhein-Westfalen", "DE-NW", "WESel", true, ""},
	{"WF", "Wolfenbüttel", "Niedersachsen", "DE-NI", "WolFenbüttel", true, ""},
	{"WG", "Ravensburg", "Baden-Württemberg", "DE-BW", "WanGen", true, ""},
	{"WHV", "Wilhelmshaven, Stadt", "Niedersachsen", "DE-NI", "WilhelmsHaVen", true, ""},
	{"WI", "Wiesbaden, Stadt", "Hessen", "DE-HE", "WIesbaden", true, ""},
	{"WIL", "Bernkastel-Wittlich", "Rheinland-Pfalz", "DE-RP", "WIttLich", true, ""},
	{"WIS", "Nordwestmecklenburg", "Mecklenburg-Vorpommern", "DE-MV", "WISmar", true, ""},
	{"WIT", "Ennepe-Ruhr-Kreis", "Nordrhein-Westfalen", "DE-NW", "WITten", true, ""},
	{"WIZ", "Werra-Meißner-Kreis", "Hessen", "DE-HE", "WItZenhausen", true, ""},
	{"WK", "Ostprignitz-Ruppin", "Brandenburg", "DE-BB", "WittstocK", true, ""},
	{"WL", "Harburg", "Niedersachsen", "DE-NI", "Winsen (Luhe)", true, ""},
	{"WLG", "Vorpommern-Greifswald", "Mecklenburg-Vorpommern", "DE-MV", "WoLGast", true, ""},
	{"WM", "Weilheim-Schongau", "Bayern", "DE-BY", "WeilheiM", true, ""},
	{"WMS", "Börde", "Sachsen-Anhalt", "DE-ST", "WolMirStedt", true, ""},
	{"WN", "Rems-Murr-Kreis", "Baden-Württemberg", "DE-BW", "WaiblingeN", true, ""},
	{"WND", "St. Wendel", "Saarland", "DE-SL", "WeNDel", true, ""},
	{"WO", "Worms, Stadt", "Rheinland-Pfalz", "DE-RP", "WOrms", true, ""},
	{"WOB", "Wolfsburg, Stadt", "Niedersachsen", "DE-NI", "WOlfsBurg", true, ""},
	{"WOH", "Kassel", "Hessen", "DE-HE", "WOlfHagen", true, ""},
	{"WOL", "Freudenstadt / Ortenaukreis", "Baden-Württemberg", "DE-BW", "WOLfach", true, ""},
	{"WOR", "Bad Tölz-Wolfratshausen / München / Starnberg", "Bayern", "DE-BY", "WOlfRatshausen", true, ""},
	{"WOS", "Freyung-Grafenau", "Bayern", "DE-BY", "WOlfStein", true, ""},
	{"WR", "Harz", "Sachsen-Anhalt", "DE-ST", "WernigeRode", true, ""},
	{"WRN", "Mecklenburgische Seenplatte", "Mecklenburg-Vorpommern", "DE-MV", "WaReN", true, ""},
	{"WS", "Mühldorf am Inn / Rosenheim", "Bayern", "DE-BY", "WasSerburg", true, ""},
	{"WSF", "Burgenlandkreis", "Sachsen-Anhalt", "DE-ST", "WeisSenFels", true, ""},
	{"WST", "Ammerland", "Niedersachsen", "DE-NI", "WesterSTede", true, ""},
	{"WSW", "Görlitz", "Sachsen", "DE-SN", "WeisSWasser", true, ""},
	{"WT", "Waldshut", "Baden-Württemberg", "DE-BW", "WaldshuT", true, ""},
	{"WTL", "Osnabrück", "Niedersachsen", "DE-NI", "WitTLage", true, ""},
	{"WTM", "Wittmund", "Niedersachsen", "DE-NI", "WitTMund", true, ""},
	{"WUG", "Weißenburg-Gunzenhausen", "Bayern", "DE-BY", "WeißenbUrG", true, ""},
	{"WUN", "Wunsiedel im Fichtelgebirge", "Bayern", "DE-BY", "WUNsiedel", true, ""},
	{"WUR", "Leipzig", "Sachsen", "DE-SN", "WURzen", true, ""},
	{"WW", "Westerwaldkreis", "Rheinland-Pfalz", "DE-RP", "WesterWald", true, ""},
	{"WZ", "Lahn-Dill-Kreis", "Hessen", "DE-HE", "WetZlar", true, ""},
	{"WZL", "Börde", "Sachsen-Anhalt", "DE-ST", "WanZLeben", true, ""},
	{"WÜ", "Würzburg", "Bayern", "DE-BY", "WÜrzburg", true, ""},
	{"WÜM", "Cham", "Bayern", "DE-BY", "WaldMÜnchen", true, ""},
	{"Z", "Zwickau", "Sachsen", "DE-SN", "Zwickau", true, ""},
	{"ZE", "Anhalt-Bitterfeld", "Sachsen-Anhalt", "DE-ST", "ZErbst", true, ""},
	{"ZEL", "Cochem-Zell", "Rheinland-Pfalz", "DE-RP", "ZELl", true, ""},
	{"ZI", "Görlitz", "Sachsen", "DE-SN", "ZIttau", true, ""},
	{"ZIG", "Schwalm-Eder-Kreis", "Hessen", "DE-HE", "ZIeGenhain", true, ""},
	{"ZP", "Erzgebirgskreis", "Sachsen", "DE-SN", "ZschoPau", true, ""},
	{"ZR", "Greiz", "Thüringen", "DE-TH", "ZeulenRoda", true, ""},
	{"ZS", "Teltow-Fläming", "Brandenburg", "DE-BB", "ZoSsen", true, ""},
	{"ZW", "Südwestpfalz / Zweibrücken, Stadt", "Rheinland-Pfalz", "DE-RP", "ZWeibrücken", true, ""},
	{"ZZ", "Burgenlandkreis", "Sachsen-Anhalt", "DE-ST", "ZeitZ", true, ""},
	{"ÖHR", "Hohenlohekreis", "Baden-Württemberg", "DE-BW", "ÖHRingen", true, ""},
	{"ÜB", "Ravensburg / Bodenseekreis / Sigmaringen", "Baden-Württemberg", "DE-BW", "ÜBerlingen", true, ""},
}

func init() {
	m.Register(func(app core.App) error {
		return upCreateKennzeichen(app)
	}, func(app core.App) error {
		return downDropKennzeichen(app)
	})
}

// upCreateKennzeichen creates the collection and seeds all records.
func upCreateKennzeichen(app core.App) error {
	// ── 1. Create the collection ────────────────────────────────────────────
	collection := core.NewBaseCollection("kennzeichen")

	// Public read access; no write access from API (managed via migrations/admin)
	collection.ListRule = types.Pointer("")   // public
	collection.ViewRule = types.Pointer("")   // public
	collection.CreateRule = nil // admin only
	collection.UpdateRule = nil // admin only
	collection.DeleteRule = nil // admin only

	collection.Fields.Add(
		&core.TextField{
			Name:     "code",
			Required: true,
			Max:      3,
		},
		&core.TextField{
			Name:     "district_name",
			Required: true,
			Max:      200,
		},
		&core.TextField{
			Name:     "bundesland",
			Required: true,
			Max:      50,
		},
		&core.TextField{
			Name:     "bundesland_iso",
			Required: true,
			Max:      6,
		},
		&core.TextField{
			Name: "derivation",
			Max:  200,
		},
		&core.BoolField{
			Name: "active",
		},
		&core.TextField{
			Name: "notes",
			Max:  500,
		},
	)

	// Unique index on `code` for fast lookups
	collection.AddIndex("idx_kennzeichen_code_unique", true, "code", "")
	// Index on bundesland for filtering by state
	collection.AddIndex("idx_kennzeichen_bundesland", false, "bundesland_iso", "")
	// Index on active status
	collection.AddIndex("idx_kennzeichen_active", false, "active", "")

	if err := app.Save(collection); err != nil {
		return err
	}

	// ── 2. Seed all records in a single transaction ─────────────────────────
	return app.RunInTransaction(func(txApp core.App) error {
		col, err := txApp.FindCollectionByNameOrId("kennzeichen")
		if err != nil {
			return err
		}

		for _, entry := range kennzeichenData {
			record := core.NewRecord(col)
			record.Set("code", entry.Code)
			record.Set("district_name", entry.District)
			record.Set("bundesland", entry.Bundesland)
			record.Set("bundesland_iso", entry.BundeslandISO)
			record.Set("derivation", entry.Derivation)
			record.Set("active", entry.Active)
			record.Set("notes", entry.Notes)

			if err := txApp.Save(record); err != nil {
				return err
			}
		}
		return nil
	})
}

// downDropKennzeichen removes the collection (used by `migrate down`).
func downDropKennzeichen(app core.App) error {
	collection, err := app.FindCollectionByNameOrId("kennzeichen")
	if err != nil {
		return err
	}
	return app.Delete(collection)
}
