#!/bin/sh
set -e

# Write runtime PocketBase URL into /srv/env.js.
# This overwrites the build-time default so the container is re-configurable
# at runtime without rebuilding the image.
#
# Usage: set PB_URL env var when running the container, e.g.
#   docker run -e PB_URL=https://pb.example.com ghcr.io/.../mkz-website:v1.0.0
cat > /srv/env.js << EOF
// Generated by docker-entrypoint.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
window.__ENV__ = {
  PB_URL: "${PB_URL:-http://localhost:8090}"
};
EOF

exec caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
